# Generated by Django 3.0.3 on 2020-03-19 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=30)),
                ('is_parent', models.BooleanField(default=False)),
                ('parentcat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imagier.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('label', models.CharField(max_length=55)),
                ('upper_label', models.CharField(max_length=55)),
                ('picture', models.URLField(blank=True, max_length=1000)),
                ('category', models.ManyToManyField(blank=True, related_name='item', to='imagier.Category')),
                ('user', models.ManyToManyField(blank=True, related_name='item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item', models.ManyToManyField(related_name='favourites', to='imagier.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
