# Generated by Django 3.0.3 on 2020-02-27 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imagier', '0002_auto_20200226_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('item', models.ManyToManyField(related_name='item', to='imagier.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
