# Generated by Django 3.0.3 on 2020-03-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagier', '0003_auto_20200227_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
    ]
