# Generated by Django 3.0.3 on 2020-03-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagier', '0004_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.URLField(blank=True, max_length=500, unique=True),
        ),
    ]
