# Generated by Django 3.0.3 on 2020-03-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagier', '0006_auto_20200304_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='upper_label',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
