# Generated by Django 3.0.3 on 2020-03-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagier', '0007_item_upper_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
