# Generated by Django 3.0.3 on 2020-03-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagier', '0008_auto_20200308_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='item',
            field=models.ManyToManyField(related_name='favourites', to='imagier.Item'),
        ),
    ]
