# Generated by Django 3.0.3 on 2020-03-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagier', '0009_auto_20200310_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
