# Generated by Django 3.0.3 on 2020-03-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagier', '0010_auto_20200310_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imagier.Category'),
        ),
    ]
