# Generated by Django 3.0.3 on 2020-03-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagier', '0011_auto_20200311_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='upper_label',
            field=models.CharField(max_length=55),
        ),
    ]
